
-- Dungeon Master (This one spits out fireballs at you)

mobs:register_mob("mobs:dungeon_master2", {
	type = "monster",
	hp_min = 25,
	hp_max = 35,
	collisionbox = {-0.7, -0.01, -0.7, 0.7, 2.6, 0.7},
	visual = "mesh",
	mesh = "mobs_dungeon_master.x",
	--textures = {"mobs_dungeon_master.png"},
	available_textures = {
		total = 1,
		texture_1 = {"mobs_dungeon_master2.png"},
	},
	visual_size = {x=8, y=8},
	makes_footstep_sound = true,
	sounds = {
		random = "mobs_dungeonmaster",
		attack = "mobs_dungeonmaster",
	},
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 4,
	drops = {
		{name = "default:mese_crystal_fragment",
		chance = 1,
		min = 1,
		max = 3,},
		{name = "default:diamond",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:mese_crystal",
		chance = 2,
		min = 1,
		max = 2,},
		{name = "default:mese",
		chance = 30,
		min = 1,
		max = 1,},
	},
	armor = 60,
	drawtype = "front",
	water_damage = 1,
	lava_damage = 1,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "shoot",
	arrow = "mobs:fireball",
	shoot_interval = 2.0,
	sounds = {
		attack = "mobs_fireball",
	},
	animation = {
		stand_start = 0,
		stand_end = 19,
		walk_start = 20,
		walk_end = 35,
		punch_start = 36,
		punch_end = 48,
		speed_normal = 15,
		speed_run = 15,
	},
	jump = true,
	step = 0.5,
	shoot_offset = 0,
	blood_texture = "mobs_blood.png",
})
mobs:spawn_specific("mobs:dungeon_master2", {"default:stone"}, "air", 0, 1, 100, 7000, 1, -30000, -7500)

